apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pvc
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 200M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
  labels:
    app: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki-app
        image: mediawiki-apache:1.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  selector:
    app: mediawiki
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80