apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pvc
  labels:
    app: mediawiki
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
  labels:
    app: mediawiki
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      containers:
      - name: mediawiki-app
        image: ramakrishnakaushik97/mediawiki-apache:1.0
        envFrom:
          - configMapRef:
              name: app-config
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mediawiki-persistent-storage
          mountPath: /var/lib/app
      volumes:
      - name: mediawiki-persistent-storage
        persistentVolumeClaim:
          claimName: mediawiki-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
spec:
  selector:
    app: mediawiki
    tier: frontend
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
  
